# Generated by Django 2.2 on 2020-06-04 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_planner_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='grocery_planner_app.User'),
            preserve_default=False,
        ),
    ]
