# Generated by Django 2.2 on 2020-05-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_planner_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.CharField(default='Food', max_length=255),
            preserve_default=False,
        ),
    ]
