# Generated by Django 2.2 on 2020-05-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_planner_app', '0002_auto_20200530_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.CharField(default='Sample instructions here', max_length=255),
            preserve_default=False,
        ),
    ]
