# Generated by Django 2.2 on 2020-06-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_planner_app', '0002_recipe_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
