# Generated by Django 2.2 on 2020-06-04 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_planner_app', '0003_ingredient_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='scheduler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_meals', to='grocery_planner_app.User'),
            preserve_default=False,
        ),
    ]
